version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - my-network

  procesamientodepagos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procesamientodepagos
    depends_on:
      - rabbitmq
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
